// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDl6v5m759zXfOYxV6OnDNHnTNBM4SppE',
    appId: '1:366265270631:web:46b6fe6c55866be8132fc2',
    messagingSenderId: '366265270631',
    projectId: 'dtfly-d8997',
    authDomain: 'dtfly-d8997.firebaseapp.com',
    storageBucket: 'dtfly-d8997.firebasestorage.app',
    measurementId: 'G-88CZT9S8NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6gGhe5S1z4Lk0sKsFwS8KvrxPgUfeco',
    appId: '1:366265270631:android:3283c136f02f0a73132fc2',
    messagingSenderId: '366265270631',
    projectId: 'dtfly-d8997',
    storageBucket: 'dtfly-d8997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR44110veg64SiyF2hP7PSGPPymB86_l0',
    appId: '1:366265270631:ios:e2435884598129ab132fc2',
    messagingSenderId: '366265270631',
    projectId: 'dtfly-d8997',
    storageBucket: 'dtfly-d8997.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR44110veg64SiyF2hP7PSGPPymB86_l0',
    appId: '1:366265270631:ios:e2435884598129ab132fc2',
    messagingSenderId: '366265270631',
    projectId: 'dtfly-d8997',
    storageBucket: 'dtfly-d8997.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDl6v5m759zXfOYxV6OnDNHnTNBM4SppE',
    appId: '1:366265270631:web:fd2ec34caae9f9c9132fc2',
    messagingSenderId: '366265270631',
    projectId: 'dtfly-d8997',
    authDomain: 'dtfly-d8997.firebaseapp.com',
    storageBucket: 'dtfly-d8997.firebasestorage.app',
    measurementId: 'G-J086F5G7G1',
  );
}
